### ISSUE TITLE
Gem currently broken

### ISSUE THREAD

**Issue by Plaristote** [markpent/SandboxedERB#2]
Greetings,

There is probably something wrong with my environment, but I've been trying to get this gem to work with Ruby 1.9.3 and 2.0.0 unsuccessfully.
More or less half the unit test are failing, and in my Rails application it seems that all templates containing the <%= %> delimiters fail to compile no matter what is inside those. The templates from the README also fail to compile in the same way.

From what I've seen, it seems the API of one of the requirements has changed. I'm having trouble finding proper versions, but it seems like this could be fixed just by changing the Gemfile.

**Comment by markpent** [comment]
This is a proof on concept for a direction my company will eventually be taking.. until then i don't have the time fix this...
I was able to pass all tests using 1.9.3-p125 with the gemset:
activesupport (3.2.11)
bourne (1.1.2)
bundler (1.3.5)
git (1.2.5)
i18n (0.6.1)
jeweler (1.6.4)
metaclass (0.0.1)
mocha (0.10.5)
multi_json (1.5.0)
partialruby (0.2.2)
rake (10.0.3)
ruby2ruby (1.3.1)
ruby_parser (2.3.1)
sexp_processor (3.2.0)
shoulda (3.3.2)
shoulda-context (1.0.2)
shoulda-matchers (1.4.2)
simplecov (0.7.1)
simplecov-html (0.7.1)

Hopefully that will help you find a combination of gems that will work...goodluck :)

**Comment by Plaristote** [comment]
Forcing activesupport to 3.2.11 and sexp_processor to 3.2.0 was all that was needed for the test to pass again !
Thanks a lot !
